version: "3.8"

services:
  opc_ua_client:
    container_name: s4_g1_opc_ua_client
    build:
      context: .
      dockerfile: Docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8001:8001
    command: echo hello